#!/usr/bin/env bash
# Redirection
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > "/var/www/html/index.html"
RedirectConfig="server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
        location / {
                rewrite ^/redirect_me/?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}"
echo "$RedirectConfig" > "/etc/nginx/sites-available/default"
sudo service nginx restart
