#!/usr/bin/env bash
# Not Found page 404
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > "/var/www/html/index.html"
echo "Ceci n'est pas une page" > "/var/www/html/404.html"
RedirectConfig="server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
        # Custom error pages
        error_page 404 /404.html;
        location / {
                try_files $uri $uri/ =404;
                rewrite ^/redirect_me/?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
        location = /404.html {
                root /var/www/html;
        }
}"
echo "$RedirectConfig" > "/etc/nginx/sites-available/default"
sudo service nginx restart
