#!/usr/bin/env bash
#install load balance
sudo apt -y update
sudo apt install -y haproxy

echo "
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    option http-server-close
    server 512646-web-01 52.3.245.179:80 check
    server 512646-web-02 54.160.107.3:80 check" >> "/etc/haproxy/haproxy.cfg"
service haproxy restart
