#!/usr/bin/env bash
#Write a Bash script that displays:The content of the current directory, In a list format
LIST="$(ls)"
for i in $LIST; do
    NEWNAME=$(ls "$i" | sed -e 's/.*-//')
    echo $NEWNAME
done
