#!/usr/bin/env bash
# This script change the ip of localhost and facebook records
ips=("127.0.0.2" "8.8.8.8")
host_names=("localhost" "facebook.com")
for index in "${!ips[@]}"; do
    ip="${ips[$index]}"
    host_name="${host_names[$index]}"
    if grep -q "$host_name" /etc/hosts; then
        sed -i "s/.*$host_name/$ip $host_name/" /etc/hosts
    else
        echo "$ip $host_name" >> /etc/hosts
fi
done
